// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: api/proto/product/product_proto.proto

package productv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductGrpcServiceClient is the client API for ProductGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductGrpcServiceClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	ReduceStock(ctx context.Context, in *ReduceStockRequest, opts ...grpc.CallOption) (*ReduceStockResponse, error)
}

type productGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductGrpcServiceClient(cc grpc.ClientConnInterface) ProductGrpcServiceClient {
	return &productGrpcServiceClient{cc}
}

func (c *productGrpcServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, "/product.v1.ProductGrpcService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productGrpcServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, "/product.v1.ProductGrpcService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productGrpcServiceClient) ReduceStock(ctx context.Context, in *ReduceStockRequest, opts ...grpc.CallOption) (*ReduceStockResponse, error) {
	out := new(ReduceStockResponse)
	err := c.cc.Invoke(ctx, "/product.v1.ProductGrpcService/ReduceStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductGrpcServiceServer is the server API for ProductGrpcService service.
// All implementations must embed UnimplementedProductGrpcServiceServer
// for forward compatibility
type ProductGrpcServiceServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	ReduceStock(context.Context, *ReduceStockRequest) (*ReduceStockResponse, error)
	mustEmbedUnimplementedProductGrpcServiceServer()
}

// UnimplementedProductGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductGrpcServiceServer struct {
}

func (UnimplementedProductGrpcServiceServer) CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductGrpcServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductGrpcServiceServer) ReduceStock(context.Context, *ReduceStockRequest) (*ReduceStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReduceStock not implemented")
}
func (UnimplementedProductGrpcServiceServer) mustEmbedUnimplementedProductGrpcServiceServer() {}

// UnsafeProductGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductGrpcServiceServer will
// result in compilation errors.
type UnsafeProductGrpcServiceServer interface {
	mustEmbedUnimplementedProductGrpcServiceServer()
}

func RegisterProductGrpcServiceServer(s grpc.ServiceRegistrar, srv ProductGrpcServiceServer) {
	s.RegisterService(&ProductGrpcService_ServiceDesc, srv)
}

func _ProductGrpcService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductGrpcServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.v1.ProductGrpcService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductGrpcServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductGrpcService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductGrpcServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.v1.ProductGrpcService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductGrpcServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductGrpcService_ReduceStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductGrpcServiceServer).ReduceStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.v1.ProductGrpcService/ReduceStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductGrpcServiceServer).ReduceStock(ctx, req.(*ReduceStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductGrpcService_ServiceDesc is the grpc.ServiceDesc for ProductGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.v1.ProductGrpcService",
	HandlerType: (*ProductGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductGrpcService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductGrpcService_GetProduct_Handler,
		},
		{
			MethodName: "ReduceStock",
			Handler:    _ProductGrpcService_ReduceStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/product/product_proto.proto",
}
