grpc:
  ip: 127.0.0.1
  name: order-service-grpc
  port: 50003
database:
  host: localhost
  port: 55432
  username: ai_user
  password: ai_pass
  database: micro_shop_user
etcd:
  ip: 127.0.0.1
  port: 2379
  timeout: 10